/* Generated by Yosys 0.55 (git sha1 60f126cd00c94892782470192d6c9f7abebe7c05, clang++ 17.0.0 -fPIC -O3) */

module full_adder_simple(clk_i, reset_n_i, a_i, b_i, cin_i, sum_o, cout_o);
  wire _0_;
  wire _1_;
  wire _2_;
  input a_i;
  wire a_i;
  input b_i;
  wire b_i;
  input cin_i;
  wire cin_i;
  input clk_i;
  wire clk_i;
  output cout_o;
  wire cout_o;
  input reset_n_i;
  wire reset_n_i;
  output sum_o;
  wire sum_o;
  \$_XNOR_  _3_ (
    .A(b_i),
    .B(a_i),
    .Y(_0_)
  );
  \$_XNOR_  _4_ (
    .A(_0_),
    .B(cin_i),
    .Y(sum_o)
  );
  \$_AND_  _5_ (
    .A(b_i),
    .B(a_i),
    .Y(_1_)
  );
  \$_ANDNOT_  _6_ (
    .A(cin_i),
    .B(_0_),
    .Y(_2_)
  );
  \$_OR_  _7_ (
    .A(_2_),
    .B(_1_),
    .Y(cout_o)
  );
endmodule
